"""Procedural sand-desert texture painter for the Terrain shader.

Generates a tileable RGB diffuse map with the visual character of
a real desert: warm tan sand, large slow direction-varying wind
ripples, smaller cross-ripples, fine grain noise, and a fake-light
gradient shade so the surface reads with depth even without a
normal map.

Output is a PNG saved to `resources/sand_painted.png` by default.
The terrain auto-loader picks up that file ahead of any
user-supplied `sand.png`.

Tileability
-----------
Every layer in this painter is constructed to wrap perfectly at
the texture edges so GL_REPEAT can stitch tiles without visible
seams:

  * The two ripple sin-wave layers run at frequencies chosen so
    that `freq * tile_meters` is an integer (whole cycles per
    tile).
  * Every noise / fBm layer is generated by filtering a random
    field in the FFT domain.  The DFT inherently assumes
    periodicity, so any filter that operates on the spectrum
    produces a spatial-domain output that already wraps.
  * The fake-shading gradient at the end uses a CYCLIC central-
    difference (np.roll +/-1 on each axis) instead of np.gradient,
    which has open boundaries and would leave a visible "frame"
    around each tile.

Usage
-----
    python cust_tools/paint_sand_desert.py
    python cust_tools/paint_sand_desert.py --size 8192
    python cust_tools/paint_sand_desert.py --size 4096 --seed 7
    python cust_tools/paint_sand_desert.py --out resources/my_sand.png

Notes on size
-------------
GL_MAX_TEXTURE_SIZE is 16384 on every modern desktop GPU.  At
that size the GPU will hold ~1 GB after mipmap generation; CPU
painting peaks around 4-5 GB during the FFT passes.  Default is
8192 (~256 MB GPU, ~1.5 GB CPU peak) which is the practical
sweet spot at the standard 50 m tile size (~6 mm/pixel
resolution).
"""

import argparse
import os
import sys
import time

import numpy as np


# ---------------------------------------------------------------------------
# FFT-based tileable noise primitives.
#
# Why FFT: the discrete Fourier transform inherently treats the
# input as periodic (the DFT basis is sin/cos at integer
# frequencies that fit exactly into the array size).  So if we
# generate any random field and filter its spectrum, the inverse
# transform comes out periodic as a free side-effect.  Compared
# to "make_tileable_via_crossfade" tricks, this is mathematically
# clean and produces no blend-artefact ghosts at the seams.
# ---------------------------------------------------------------------------
def _radial_freq_grid(size):
    """Return a (size, size//2 + 1) array of frequency magnitudes
    in cycles-per-tile, matching the layout that np.fft.rfft2
    produces.  Cached on the function attribute the first time
    it's called for a given size, since we use it on every layer.
    """
    cached = getattr(_radial_freq_grid, '_cache', {})
    if size in cached:
        return cached[size]
    fy = np.fft.fftfreq(size).astype(np.float32)        # [-0.5, 0.5)
    fx = np.fft.rfftfreq(size).astype(np.float32)       # [0, 0.5]
    FY, FX = np.meshgrid(fy, fx, indexing='ij')
    # Convert from cycles-per-pixel to cycles-per-tile by
    # multiplying by `size` (the tile is `size` pixels wide).
    radial = np.sqrt(FY * FY + FX * FX).astype(np.float32) * float(size)
    cached[size] = radial
    _radial_freq_grid._cache = cached
    return radial


def tileable_noise(size, cycles_per_tile, seed):
    """One layer of tileable low-pass-filtered Gaussian noise.

    Args:
        size            (int):   output edge length in pixels.
        cycles_per_tile (float): smooth Gaussian cutoff in cycles
            across the full tile.  Higher = finer detail.
            ~50 is medium grain, ~5 is broad rolling features.
        seed            (int):   RNG seed.
    Returns:
        np.ndarray (size, size) float32 in [0, 1], wrapping
        perfectly at all four edges.
    """
    rng    = np.random.default_rng(int(seed))
    raw    = rng.standard_normal((size, size)).astype(np.float32)
    spec   = np.fft.rfft2(raw)
    radial = _radial_freq_grid(size)
    # Soft Gaussian cutoff in the frequency domain.  e^(-(f/c)^2)
    # falls off smoothly past `cycles_per_tile` so we don't get
    # ringing in the spatial output (a hard cutoff would).
    cutoff = max(float(cycles_per_tile), 1e-9)
    mask   = np.exp(-(radial / cutoff) ** 2).astype(np.float32)
    spec  *= mask
    out    = np.fft.irfft2(spec, s=(size, size)).astype(np.float32)
    # Normalise to [0, 1].  np.fft round-trips give arbitrary
    # amplitude depending on the cutoff; a clean per-layer
    # rescale keeps fBm summation balanced.
    lo, hi = float(out.min()), float(out.max())
    return (out - lo) / max(hi - lo, 1e-9)


def tileable_fbm(size, octaves, base_cycles_per_tile,
                 persistence, seed):
    """Fractal-Brownian sum of tileable_noise octaves.

    Each octave doubles the frequency cutoff and halves the
    amplitude (default persistence 0.5).  Independent random
    seeds per octave so the layers don't correlate.
    """
    out    = np.zeros((size, size), dtype=np.float32)
    amp    = 1.0
    cycles = float(base_cycles_per_tile)
    norm   = 0.0
    for o in range(int(octaves)):
        out  += tileable_noise(size, cycles, seed + o * 17) * amp
        norm += amp
        amp  *= persistence
        cycles *= 2.0
    if norm > 0.0:
        out /= norm
    return out


def cyclic_gradient(arr):
    """Cyclic central-difference gradient (dy, dx).

    Uses np.roll +/-1 on each axis so the boundary samples wrap to
    the opposite edge, preserving tileability.  np.gradient does
    one-sided differences at the boundaries, which leaves a thin
    "frame" of mismatched shading around each tile when GL_REPEAT
    stitches them.
    """
    dy = (np.roll(arr, -1, axis=0) - np.roll(arr, 1, axis=0)) * 0.5
    dx = (np.roll(arr, -1, axis=1) - np.roll(arr, 1, axis=1)) * 0.5
    return dy, dx


# ---------------------------------------------------------------------------
# The painter.
#
# Layered build, each fold-in releases the layer's float32 array
# as soon as the running output absorbs it -- keeps peak memory
# closer to 4 * size^2 * 4 bytes (~1 GB at 8192) than the naive
# "hold all layers in memory" approach.
# ---------------------------------------------------------------------------
def paint_sand(size, out_path, tile_meters, seed):
    print(f"Generating {size}x{size} sand at {tile_meters} m / tile "
          f"(seed={seed}) -- tileable build")
    t0 = time.time()

    # Coordinate grid in METRES so noise frequencies are in cycles/m.
    # The grid is the same as a normalised [0..1] grid scaled by
    # `tile_meters`; the sin waves below use it directly.
    coords = np.linspace(0.0, tile_meters, size, endpoint=False,
                         dtype=np.float32)
    X, Y   = np.meshgrid(coords, coords, indexing='xy')

    # ---- 1+2. Domain-warp fields (MEDIUM + SMALL) --------------------
    # Two warp passes, deliberately HIGH-frequency so neither leaves
    # a visible "phase" across the tile when GL averages it down to
    # coarse mips at distance.  The previous build used a very low-
    # frequency big-amplitude warp which created visible per-tile
    # colour shifts at far mip levels (the rectangle-grid artefact
    # the user spotted).
    #
    #   wx_med / wy_med -- ~5 cycles per tile, modest amplitude.
    #     Bends the ripple lines in metre-scale lobes -- enough
    #     organic curving without low-freq tile-phase variation.
    #   wx_fine / wy_fine -- ~10 cycles per tile, low amplitude.
    #     Adds the small ripple-meander wobble at sub-metre scale.
    #
    # Both warps are FFT-built tileable noise so the displacement
    # fields wrap perfectly at the tile edges.
    print("  layer 1/6  warp (medium lobes)")
    med_amp  = tile_meters * 0.04    # up to 2 m on a 50 m tile
    fine_amp = tile_meters * 0.02    # up to 1 m fine wiggle
    wx_med = (tileable_fbm(size, octaves=2, base_cycles_per_tile=5.0,
                           persistence=0.5, seed=seed + 1)
              - 0.5) * (2.0 * med_amp)
    wy_med = (tileable_fbm(size, octaves=2, base_cycles_per_tile=5.0,
                           persistence=0.5, seed=seed + 2)
              - 0.5) * (2.0 * med_amp)

    print("  layer 2/6  warp (fine wiggle)")
    wx_fine = (tileable_fbm(size, octaves=3, base_cycles_per_tile=10.0,
                            persistence=0.5, seed=seed + 3)
               - 0.5) * (2.0 * fine_amp)
    wy_fine = (tileable_fbm(size, octaves=3, base_cycles_per_tile=10.0,
                            persistence=0.5, seed=seed + 4)
               - 0.5) * (2.0 * fine_amp)

    DX = X + wx_med + wx_fine
    DY = Y + wy_med + wy_fine
    del wx_med, wy_med, wx_fine, wy_fine, X, Y

    # ---- 3. Primary ripples ------------------------------------------
    # Axis-aligned sin wave on X.  Frequency 1.5 cycles/m at 50 m
    # tile = exactly 75 whole cycles per tile -- integer = perfect
    # periodicity.  Phase shifted by the warped DX so the ripple
    # lines bend across the tile but each individual sample still
    # sees a phase that wraps cleanly at the edges.
    print("  layer 3/6  primary ripples")
    primary_freq = 1.5
    primary = np.sin(DX * (2.0 * np.pi * primary_freq)) * 0.5 + 0.5
    del DX

    # ---- 4. Cross-ripples --------------------------------------------
    # Orthogonal axis-aligned sin on Y.  0.7 * 50 = 35 cycles per
    # tile -- integer, tileable.  Lower amplitude than the primary
    # so it adds variety without dominating.
    print("  layer 4/6  cross ripples")
    cross_freq = 0.7
    cross   = np.sin(DY * (2.0 * np.pi * cross_freq)) * 0.5 + 0.5
    surface = primary * 0.75 + cross * 0.25
    del primary, cross, DY

    # ---- 5. Fine grain noise -----------------------------------------
    # High-freq detail: cutoff at size/8 cycles per tile gives
    # very fine speckle.  Bumped via fBm so it's not pure white
    # noise (would alias on mip-down).
    print("  layer 5/6  grain noise")
    grain_cutoff = size / 8.0
    grain   = tileable_fbm(size, octaves=3,
                           base_cycles_per_tile=grain_cutoff,
                           persistence=0.55, seed=seed + 5)
    surface = np.clip(surface * 0.88 + grain * 0.12, 0.0, 1.0)
    del grain

    # ---- 5b. Low-frequency high-pass to kill mip-blockiness ----------
    # The "rectangle grid at distance" artefact comes from any
    # low-frequency variation surviving the GL mip-down chain --
    # at far enough distance every tile renders as ~one pixel,
    # whose colour is the tile's average; if neighbouring tiles
    # happen to land on different phases of the low-freq content,
    # they show as different colours -> visible grid.
    #
    # Fix: FFT-domain high-pass.  Compute a Gaussian low-pass
    # version of the surface, subtract it, renormalise.  Anything
    # below ~12 cycles per tile (= ~4 m features at 50 m tile)
    # gets suppressed, so block-mean at any mip level converges
    # to a near-constant.
    print("        high-pass anti-mip-block")
    spec    = np.fft.rfft2(surface)
    radial  = _radial_freq_grid(size)
    lp_cut  = 12.0    # cycles per tile -- anything coarser gets killed
    lp_mask = np.exp(-(radial / lp_cut) ** 2).astype(np.float32)
    low     = np.fft.irfft2(spec * lp_mask,
                            s=(size, size)).astype(np.float32)
    high    = surface - low
    del spec, lp_mask, low
    # Renormalise the high-pass back into [0, 1].  The high-pass
    # output is centred near 0; we want a positive surface curve.
    lo, hi  = float(high.min()), float(high.max())
    surface = np.clip((high - lo) / max(hi - lo, 1e-9), 0.0, 1.0)
    del high

    # ---- 6. Compose colour + fake shading ----------------------------
    # NOTE: tonal-drift layer was removed -- its 2-cycles-per-tile
    # period was visible at far mip levels as per-tile colour
    # variation (the "rectangle grid" artefact).  Sand reads as
    # uniform-ish at distance now; close-up detail still comes from
    # the warped ripples + grain.
    print("  layer 6/6  colour + shade")
    light = np.array([0.93, 0.79, 0.58], dtype=np.float32)   # crest
    mid   = np.array([0.82, 0.65, 0.43], dtype=np.float32)   # face
    dark  = np.array([0.58, 0.42, 0.26], dtype=np.float32)   # trough

    # Snapshot the surface AS IT IS now -- this is the height-
    # field the colour ramp uses + the same data we'll save out
    # as the grayscale displacement companion.  Saved before the
    # palette + shading multiply so the heightmap is pure ripple
    # geometry without the fake-light gradient baked in.
    _height_for_save = surface.copy()

    t = np.clip(surface, 0.0, 1.0)

    # Two-segment palette ramp (smoothstep transitions in each
    # half) so we get continuous gradient without hard banding.
    s_low  = np.clip((t - 0.00) / 0.50, 0.0, 1.0)
    s_high = np.clip((t - 0.50) / 0.50, 0.0, 1.0)
    s_low  = s_low  * s_low  * (3.0 - 2.0 * s_low)
    s_high = s_high * s_high * (3.0 - 2.0 * s_high)
    rgb_lo = (dark[None, None, :]
              + (mid[None, None, :]   - dark[None, None, :])
              * s_low [..., None])
    rgb_hi = (mid[None, None, :]
              + (light[None, None, :] - mid[None, None, :])
              * s_high[..., None])
    blend  = np.where(t[..., None] < 0.5, rgb_lo, rgb_hi).astype(np.float32)
    del rgb_lo, rgb_hi, s_low, s_high

    # Cyclic-gradient shading: dot the cyclic surface gradient
    # with a "light from upper-left" direction so ripple-faces
    # facing the light read brighter, away faces darker.  np.roll
    # central differences keep the result tileable.
    grad_y, grad_x = cyclic_gradient(surface)
    lx, ly = -0.55, -0.55
    shade  = -(grad_x * lx + grad_y * ly)
    lo, hi = np.percentile(shade, (2.0, 98.0))
    shade  = np.clip((shade - lo) / max(hi - lo, 1e-6), 0.0, 1.0)
    shade  = shade * 0.40 + 0.78           # range ~ [0.78, 1.18]
    blend  = np.clip(blend * shade[..., None], 0.0, 1.0)
    del grad_x, grad_y, shade, surface, t

    # ---- Save -------------------------------------------------------
    print(f"  saving -> {out_path}")
    out_dir = os.path.dirname(out_path)
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir, exist_ok=True)

    from PIL import Image
    img_data = (blend * 255.0 + 0.5).astype(np.uint8)
    Image.fromarray(img_data, 'RGB').save(out_path, optimize=False)

    # Also write a grayscale "height" companion next to the colour
    # PNG.  This is the post-high-pass `surface` array (the same
    # shape that drove the colour ramp) saved as 8-bit luminance.
    # The terrain loader picks it up to drive vertex displacement
    # in lock-step with the colour, so ripple-troughs on the
    # texture coincide with ripple-troughs in the geometry.
    height_path = (os.path.splitext(out_path)[0] + '_height.png')
    height_data = np.clip(_height_for_save * 255.0 + 0.5,
                          0.0, 255.0).astype(np.uint8)
    Image.fromarray(height_data, 'L').save(height_path, optimize=False)

    elapsed = time.time() - t0
    sz_mb   = os.path.getsize(out_path) / 1e6
    sz_h_mb = os.path.getsize(height_path) / 1e6
    print(f"done in {elapsed:.1f}s "
          f"(colour {sz_mb:.1f} MB; height {sz_h_mb:.1f} MB -> "
          f"{os.path.basename(height_path)})")


# ---------------------------------------------------------------------------
def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Paint a procedural, tileable sand-desert texture "
                    "for the Terrain shader.")
    parser.add_argument(
        '--size', type=int, default=8192,
        help="output texture edge length in pixels.  GPUs cap at "
             "GL_MAX_TEXTURE_SIZE = 16384; CPU painting memory peaks "
             "at roughly 5 * size^2 * 4 bytes during the FFT passes "
             "(~1.5 GB at 8192, ~6 GB at 16384).  Default 8192.")
    parser.add_argument(
        '--out', default=os.path.join('resources', 'sand_painted.png'),
        help="output PNG path.  Default: resources/sand_painted.png")
    parser.add_argument(
        '--tile-meters', type=float, default=50.0,
        help="metres covered by one tile of the texture.  Sets the "
             "physical wavelengths of the ripple layers.  Default 50.0 "
             "matches the terrain shader's default tile size.")
    parser.add_argument(
        '--seed', type=int, default=42,
        help="RNG seed.  Same seed + same params = identical output.")

    args = parser.parse_args(argv)
    if args.size < 64:
        parser.error("--size must be >= 64")
    if args.size > 16384:
        parser.error("--size must be <= 16384")

    paint_sand(size=args.size, out_path=args.out,
               tile_meters=args.tile_meters, seed=args.seed)
    return 0


if __name__ == '__main__':
    sys.exit(main())
