"""Scan ALL tanks in `tanks_index.txt` for chassis track-segment anomalies.

Coffee 2026-05-15 ("i want you to analyze all tanks.  find things
that we are missing.. some tanks have only 1/2 of the segments
needed").

Walks `<repo>/tanks_index.txt` (auto-generated by TEPY on every
ItemList rebuild, format `<nation>\\t<tier>\\t<basename>\\t<friendly>`)
and for each entry:

  1. Extracts `Chassis.primitives_processed` via the existing
     PkgExtractor (re-uses TEPY's pkg cache + path lookup so we
     don't crack 1215 zips by hand).
  2. Parses the primitive groups; collects every section whose
     name contains "track" or "chass" (case-insensitive).
  3. Classifies each section by:
        side    -- 'L', 'R', or '?' (from the name token)
        role    -- 'track' (deforming ribbon) or 'chass'
                   (rigid sub-mesh wheel / sprocket etc.)
        shape   -- True if the name contains 'Shape' (matches the
                   viewer's `name.startswith('track_') and 'Shape'
                   in name` SKIP rule)
  4. Flags anomalies:
        ASYM    -- left vs right section count differs
        HALF    -- count(visible) == count(hidden) -- this is the
                   "1/2 of segments needed" signature
        NOTRK   -- zero track sections found
        ALLSHP  -- every section matches the SKIP rule (entire
                   chassis would be invisible)
        NOSHP   -- no section matches the SKIP rule (track stays
                   visible -- some tanks legitimately render this
                   way, but we want to verify)
        ERR     -- extract / parse failed (pkg missing, mesh too
                   exotic, etc.)

Output is a TSV file (`chassis_track_scan.txt` by default).  Sort /
filter as needed::

    python cust_tools/scan_all_chassis_tracks.py
    grep -E '(ASYM|HALF)' chassis_track_scan.txt | head
    awk -F'\\t' '$11 ~ /HALF/' chassis_track_scan.txt | wc -l

Per-tank deep dive after the scan flags a suspect::

    python cust_tools/analyze_chassis_tracks.py Pl04_Pudel

Usage::

    python cust_tools/scan_all_chassis_tracks.py
    python cust_tools/scan_all_chassis_tracks.py --out /tmp/scan.txt
    python cust_tools/scan_all_chassis_tracks.py --filter '^Pl|^GB'
"""

import argparse
import os
import re
import sys
import time
from collections import Counter

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from tankExporterPy.loaders import PkgExtractor, MeshParser


# ---------------------------------------------------------------------------
# Section-name classifier
# ---------------------------------------------------------------------------
RX_SIDE_L = re.compile(r'(?:_|^)L(?:_|\d|Shape|$)|Left', re.IGNORECASE)
RX_SIDE_R = re.compile(r'(?:_|^)R(?:_|\d|Shape|$)|Right', re.IGNORECASE)


def classify(name):
    """Return (side, role, has_shape) for a section name.

    side  : 'L' / 'R' / '?'
    role  : 'track' (deforming ribbon) / 'chass' (rigid sub-mesh)
            / 'other' (anything else that happened to match the
            "contains track or chass" pre-filter)
    has_shape : True iff 'Shape' appears in the name -- this is
                what the viewer's `track_*Shape*` SKIP rule checks
    """
    has_shape = 'Shape' in name
    has_L = bool(RX_SIDE_L.search(name))
    has_R = bool(RX_SIDE_R.search(name))
    if has_L and not has_R:
        side = 'L'
    elif has_R and not has_L:
        side = 'R'
    else:
        side = '?'
    nl = name.lower()
    if nl.startswith('track'):
        role = 'track'
    elif 'chass' in nl:
        role = 'chass'
    else:
        role = 'other'
    return side, role, has_shape


def viewer_would_skip(name):
    return name.startswith('track_') and 'Shape' in name


# ---------------------------------------------------------------------------
# Tank scan
# ---------------------------------------------------------------------------
def scan_tank(pe, nation, basename):
    base = f'vehicles/{nation}/{basename}/normal/lod0'
    try:
        prim = pe.extract(f'{base}/Chassis.primitives_processed')
    except Exception as exc:
        return {'err': f'extract: {exc}', 'sections': []}
    if not prim:
        return {'err': 'no chassis.primitives_processed', 'sections': []}
    try:
        parsed = MeshParser.parse_primitives_processed(prim)
    except Exception as exc:
        return {'err': f'parse: {exc}', 'sections': []}
    sections = []
    for g in parsed:
        nm = g.get('name') or ''
        if 'track' in nm.lower() or 'chass' in nm.lower():
            side, role, has_shape = classify(nm)
            verts = g.get('vertices', {}).get('positions', [])
            sections.append({
                'name': nm, 'side': side, 'role': role,
                'has_shape': has_shape,
                'skip': viewer_would_skip(nm),
                'verts': len(verts) if verts is not None else 0,
            })
    return {'err': None, 'sections': sections}


def derive_flags(result):
    """Build the anomaly flag string from a scan result.

    Anomaly definitions, all evaluated against TRACK-role sections
    only (chassis sub-meshes are ignored for the side / count
    rules -- they have their own naming conventions).
    """
    flags = []
    if result['err']:
        flags.append('ERR')
        return flags
    tracks = [s for s in result['sections'] if s['role'] == 'track']
    if not tracks:
        flags.append('NOTRK')
        return flags
    n_L = sum(1 for s in tracks if s['side'] == 'L')
    n_R = sum(1 for s in tracks if s['side'] == 'R')
    n_skip    = sum(1 for s in tracks if s['skip'])
    n_visible = len(tracks) - n_skip
    if n_L != n_R:
        flags.append('ASYM')
    if n_skip > 0 and n_visible > 0 and n_skip == n_visible:
        flags.append('HALF')
    if n_visible == 0 and n_skip > 0:
        flags.append('ALLSHP')
    if n_skip == 0 and n_visible > 0:
        flags.append('NOSHP')
    return flags


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main(argv=None):
    p = argparse.ArgumentParser(
        description="Scan all tanks for chassis track-segment anomalies.")
    p.add_argument('--out', default=os.path.join(ROOT,
                                                  'chassis_track_scan.txt'),
        help="output TSV file path (default: chassis_track_scan.txt "
             "at repo root)")
    p.add_argument('--filter', default=None,
        help="regex; only scan basenames matching this (e.g. "
             "'^Pl|^GB' for Polish + British)")
    p.add_argument('--pkg-dir', default=None,
        help="WoT install root; reads tankExporterPy.json if not given")
    p.add_argument('--lookup-xml', default=None,
        help="TheItemList.xml path; defaults to project root copy")
    args = p.parse_args(argv)

    if args.pkg_dir is None:
        cfg_path = os.path.join(ROOT, 'tankExporterPy.json')
        if os.path.isfile(cfg_path):
            import json
            with open(cfg_path, encoding='utf-8') as f:
                cfg = json.load(f)
            pd = (cfg.get('pkg_dir') or '').strip()
            args.pkg_dir = (os.path.normpath(os.path.join(pd, '..', '..'))
                            if pd else None)
    if not args.pkg_dir or not os.path.isdir(args.pkg_dir):
        p.error("Cannot find WoT install root.  Pass --pkg-dir or set "
                "pkg_dir in tankExporterPy.json.")
    if args.lookup_xml is None:
        args.lookup_xml = os.path.join(ROOT, 'TheItemList.xml')

    tanks_index = os.path.join(ROOT, 'tanks_index.txt')
    if not os.path.isfile(tanks_index):
        p.error(f"tanks_index.txt not found at {tanks_index}.  "
                f"Run TEPY once to regenerate it (it's rebuilt on "
                f"every ItemList rebuild).")

    filt = re.compile(args.filter) if args.filter else None

    # Read the index.
    rows = []
    with open(tanks_index, encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n')
            if not line or line.startswith('#'):
                continue
            parts = line.split('\t')
            if len(parts) < 4:
                continue
            nation, tier, basename, friendly = parts[0], parts[1], parts[2], parts[3]
            if filt and not filt.search(basename):
                continue
            rows.append((nation, tier, basename, friendly))

    print(f"scanning {len(rows)} tanks ...")
    pe = PkgExtractor(args.pkg_dir, lookup_xml=args.lookup_xml)

    fp = open(args.out, 'w', encoding='utf-8')
    fp.write("nation\ttier\tbasename\tfriendly\t"
              "n_track\tL\tR\t?\thas_shape\tskip\tvisible\t"
              "flags\tsection_names\n")

    flag_counts = Counter()
    err_count = 0
    t0 = time.perf_counter()
    for i, (nation, tier, basename, friendly) in enumerate(rows):
        if i % 50 == 0 and i > 0:
            dt = time.perf_counter() - t0
            print(f"  [{i}/{len(rows)}] {dt:.1f}s, "
                  f"{i/dt:.1f} tanks/s, flags={dict(flag_counts)}")
        result = scan_tank(pe, nation, basename)
        flags = derive_flags(result)
        for f in flags:
            flag_counts[f] += 1
        if result['err']:
            err_count += 1
        tracks = [s for s in result['sections'] if s['role'] == 'track']
        n_L = sum(1 for s in tracks if s['side'] == 'L')
        n_R = sum(1 for s in tracks if s['side'] == 'R')
        n_q = sum(1 for s in tracks if s['side'] == '?')
        n_sh = sum(1 for s in tracks if s['has_shape'])
        n_sk = sum(1 for s in tracks if s['skip'])
        n_vis = len(tracks) - n_sk
        section_list = ','.join(s['name'] for s in tracks)
        fp.write(f"{nation}\t{tier}\t{basename}\t{friendly}\t"
                  f"{len(tracks)}\t{n_L}\t{n_R}\t{n_q}\t"
                  f"{n_sh}\t{n_sk}\t{n_vis}\t"
                  f"{','.join(flags) if flags else '-'}\t"
                  f"{section_list}\n")
    fp.close()
    dt = time.perf_counter() - t0
    print(f"DONE in {dt:.1f}s -- {args.out}")
    print(f"  flag totals: {dict(flag_counts)}")
    print(f"  errors     : {err_count}")
    print(f"  total tanks: {len(rows)}")

    # Per-flag suspect summary
    print(f"\n--- Suspect previews (first 10 per flag) ---")
    for flag in ('ASYM', 'HALF', 'ALLSHP', 'NOTRK', 'ERR'):
        suspects = []
        with open(args.out, encoding='utf-8') as f:
            next(f)   # header
            for line in f:
                parts = line.split('\t')
                if len(parts) < 12:
                    continue
                if flag in parts[11]:
                    suspects.append((parts[0], parts[2], parts[3],
                                      parts[11], parts[12].rstrip()))
        print(f"\n{flag}: {len(suspects)} tank(s)")
        for s in suspects[:10]:
            print(f"  [{s[0]}] {s[1]:30s} {s[2]:30s} "
                  f"flags={s[3]}  sections=[{s[4][:80]}]")


if __name__ == '__main__':
    main()
